version: '3.3'

services:
  redis:
    image: redis:4.0.6
    command: ["redis-server", "/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
      - ./data:/data

  sentinel:
    image: redis:4.0.6
    command: ["redis-sentinel", "/sentinel.conf"]
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel.conf:/sentinel.conf
    depends_on:
      - redis
