DISTINCT_DEPARTEMENTS_HAVING_OFFICES = 1
DISTINCT_DEPARTEMENTS_HAVING_OFFICES_FROM_FILE = 15

MINIMUM_OFFICES_REQUIRED_TO_TRAIN_MODEL = 0

RMSE_MAX = 5000

# 96 departements == 2 successes + 94 failures
MAXIMUM_COMPUTE_SCORE_JOB_FAILURES = 94

SCORE_REDUCING_MINIMUM_THRESHOLD = 0

DEPARTEMENTS_TO_BE_SANITY_CHECKED = ['14', '69']
