INPUT_SOURCE_FOLDER = '/srv/lbb/labonneboite/importer/tests/data'

DISTINCT_DEPARTEMENTS_HAVING_OFFICES = 15
DISTINCT_DEPARTEMENTS_HAVING_OFFICES_FROM_FILE = 15

SCORE_COEFFICIENT_OF_VARIATION_MAX = 1.0

HIGH_SCORE_COMPANIES_COUNT_MIN = 0

DEPARTEMENTS_TO_BE_SANITY_CHECKED = []

ENABLE_TIMEIT_TIMERS = False
