include:
  - project: lbb/devops-jobs
    file: devops.gitlab-ci.yml

# this should be the local file
python-tests:
  extends: .devops::python-test
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TITLE !~ /Draft.*/
      changes:
        - labonneboite/**/*
        - pyproject.toml
    - if: ( $CI_COMMIT_BRANCH == "master" &&   $CI_PIPELINE_SOURCE != 'schedule' )
      changes:
        - labonneboite/**/*
        - pyproject.toml

sonarqube:
  extends: .devops::sonarqube
  needs:
    - job: python-tests
  rules:
    - if: ( $CI_COMMIT_BRANCH == "master"  &&   $CI_PIPELINE_SOURCE != 'schedule' )
      changes:
        - labonneboite/**/*
        - pyproject.toml

pypi-publish:
  extends: .devops::pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(\+.*)?$/
