# this part should be common and maintained in another repo
include:
  - project: lbb/devops-jobs
    file: devops.gitlab-ci.yml

# this should be the local file
python-tests:
  extends: .devops::test
  after_script:
    # fix for coverage test not read by sonar
    - sed -i 's/\/labonneboite/\.\/labonneboite/g' testResults/coverage.xml
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TITLE !~ /Draft.*/
      changes:
        - labonneboite/**/*
        - pyproject.toml
    - if: ( $CI_COMMIT_BRANCH == "main" &&   $CI_PIPELINE_SOURCE != 'schedule' )
      changes:
        - labonneboite/**/*
        - pyproject.toml

sonarqube:
  extends: .devops::sonarqube
  needs:
    - job: python-tests
  rules:
    - if: ( $CI_COMMIT_BRANCH == "main"  &&   $CI_PIPELINE_SOURCE != 'schedule' )
      changes:
        - labonneboite/**/*
        - pyproject.toml

pypi-publish:
  extends: .devops::pypi-publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(\+.*)?$/

docker-publish-beta:
  extends: .devops::docker-publish
  variables:
    DOCKER_FILE: ${CI_PROJECT_DIR}/docker/v3.10/Dockerfile
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-rc\.\d+(\+.*)?$/

docker-publish-prod:
  extends: .devops::docker-publish
  variables:
    DOCKER_FILE: ${CI_PROJECT_DIR}/docker/v3.10/Dockerfile
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+(\+.*)?$/
