version: "3.7"

x-common-env: &cenv
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: labonneboite
      MYSQL_USER: labonneboite
      MYSQL_PASSWORD: labonneboite

      DB_ROOT_PASSWORD: p@ssword
      DB_DATABASE: labonneboite
      DB_NAME: labonneboite
      DB_USER: labonneboite
      DB_PASSWORD: labonneboite
      DB_PORT: 3306
      ES_HOST: elasticsearch:9200
      DB_HOST: mysql
      OFFICE_TABLE: etablissements
      LBB_ENV: development 

services:

  # ###### 3rd-party services
  # # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  # # https://www.elastic.co/blog/how-to-make-a-dockerfile-for-elasticsearch
  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:1.7.2
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - "cluster.name=lbb"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    # networks:
    #   - labonneboite_elk
    #   - labonneboite_default
    healthcheck:
      test: curl --fail localhost:9200/_cat/health || exit 1
      interval: 10s
      retries: 5
      timeout: 2s


  mysql:
    image: mysql:5.6.36
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    #restart: unless-stopped
    environment:
      <<: *cenv
    ports:
      - 3306:3306
    # networks:
    #   - labonneboite_default
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 10s
      retries: 5
      timeout: 2s

  labonneboite:
    hostname: labonneboite-backend
    restart: always
    build:
      context: .
    environment:
      <<: *cenv
    volumes:
      - ./labonneboite/logs:/labonneboite/logs
      - .:/labonneboite/src
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080
    # networks:
    #   - labonneboite_elk
    #   - labonneboite_default

# networks:
#   labonneboite_elk:
#   labonneboite_default:
