version: "3"
services:
  nginx:
    restart: always
    image: nginx:1.13
    volumes:
    - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/var/log/labonneboite:/var/log/nginx/labonneboite
    - ./nginx/labonneboite/static:/labonneboite/static
    ports:
    - ${HTTP_PORT:-8080}:8000
    depends_on:
    - labonneboite

  ###### 3rd-party services
  elasticsearch:
    extends:
      file: docker/docker-compose.yml
      service: elasticsearch

  mysql:
    extends:
      file: docker/docker-compose.yml
      service: mysql
  
  ###### Je Postule
  labonneboite:
    restart: always
    build:
      context: .
    volumes:
    - ./labonneboite/logs:/labonneboite/logs
    - .:/labonneboite/src
    depends_on:
    - elasticsearch
    - mysql
    environment:
      LBB_ENV: ${LBB_ENV:-bonaparte}

  # backups:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: dockerfile_backups
  #     args:
  #     - ENV_TYPE=${ENV_TYPE:-production}
  #     - TIMEZONE=${TIMEZONE:-Europe/Paris}
  #   hostname: backups
  #   volumes:
  #   - ./:/home/docker
  #   - ./backups/home/backups:/home/backups
  #   - /mnt:/mnt
