docs_dir: docs

theme:
  name: material
  font:
    text: "Montserrat"
    code: "Montserrat Sans"
  features:
    # - navigation.sections
    - navigation.footer
    - navigation.indexes
    - search.highlight
    - toc.follow
    - content.code.copy
    # - search.suggest
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false
  homepage: https://labonneboite.beta.pole-emploi.fr/documentation/

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Do your stuff below

repo_name: lbb
repo_url: https://git.beta.pole-emploi.fr/lbb/lbb
site_name: La Bonnne Boite v1
site_description: "La Bonne Boite"
site_author: "La Bonne Boite"

nav:
  - index.md
  - algo.md
  - ami-api-csp.md
  - code-profiling.md
  - load-testing.md
  - ogr-rome-mapping.md
  - randomization.md
  - rome-naf-mapping.md
