# coding: utf8

DPAE = 'dpae'
ALTERNANCE = 'alt'
VALUES = [DPAE, ALTERNANCE]
DEFAULT = DPAE

CONTRACT_TO_HIRING_TYPE = {'dpae': DPAE, 'alternance': ALTERNANCE}
CONTRACT_VALUES = sorted(CONTRACT_TO_HIRING_TYPE.keys())
CONTRACT_DEFAULT = 'dpae'
