
DPAE = 'dpae'
ALTERNANCE = 'alt'
VALUES = [DPAE, ALTERNANCE]
DEFAULT = DPAE

CONTRACT_DPAE = 'dpae'
CONTRACT_ALTERNANCE = 'alternance'
CONTRACT_TO_HIRING_TYPE = {CONTRACT_DPAE: DPAE, CONTRACT_ALTERNANCE: ALTERNANCE}
CONTRACT_VALUES = sorted(CONTRACT_TO_HIRING_TYPE.keys())
CONTRACT_DEFAULT = CONTRACT_DPAE
