# coding: utf8

# FIXME
ROME_DESCRIPTIONS = {'A1101': u"Conduite d'engins d'exploitation agricole et foresti\xe8re",
 'A1201': u'B\xfbcheronnage et \xe9lagage',
 'A1202': u'Entretien des espaces naturels',
 'A1203': u'Entretien des espaces verts',
 'A1204': u'Protection du patrimoine naturel',
 'A1205': u'Sylviculture',
 'A1301': u'Conseil et assistance technique en agriculture',
 'A1302': u'Contr\xf4le et diagnostic technique en agriculture',
 'A1303': u'Ing\xe9nierie en agriculture et environnement naturel',
 'A1401': u'Aide agricole de production fruiti\xe8re ou viticole',
 'A1402': u'Aide agricole de production l\xe9gumi\xe8re ou v\xe9g\xe9tale',
 'A1403': u"Aide d'\xe9levage agricole et aquacole",
 'A1404': u'Aquaculture',
 'A1405': u'Arboriculture et viticulture',
 'A1406': u'Encadrement \xe9quipage de la p\xeache',
 'A1407': u'\xc9levage bovin ou \xe9quin',
 'A1408': u"\xc9levage d'animaux sauvages ou de compagnie",
 'A1409': u'\xc9levage de lapins et volailles',
 'A1410': u'\xc9levage ovin ou caprin',
 'A1411': u'\xc9levage porcin',
 'A1412': u'Fabrication et affinage de fromages',
 'A1413': u'Fermentation de boissons alcoolis\xe9es',
 'A1414': u'Horticulture et mara\xeechage',
 'A1415': u'Equipage de la p\xeache',
 'A1416': u'Polyculture, \xe9levage',
 'A1417': u'Saliculture',
 'A1501': u'Aide aux soins animaux',
 'A1502': u'Podologie animale',
 'A1503': u'Toilettage des animaux',
 'A1504': u'Sant\xe9 animale',
 'B1101': u'Cr\xe9ation en arts plastiques',
 'B1201': u"R\xe9alisation d'objets d\xe9coratifs et utilitaires en c\xe9ramique et mat\xe9riaux de synth\xe8se",
 'B1301': u"D\xe9coration d'espaces de vente",
 'B1302': u"D\xe9coration d'objets d'art et artisanaux",
 'B1303': u'Gravure - ciselure',
 'B1401': u"R\xe9alisation d'objets en lianes, fibres et brins v\xe9g\xe9taux",
 'B1402': u'Reliure et restauration de livres et archives',
 'B1501': u"Fabrication et r\xe9paration d'instruments de musique",
 'B1601': u"M\xe9tallerie d'art",
 'B1602': u"R\xe9alisation d'objets artistiques et fonctionnels en verre",
 'B1603': u"R\xe9alisation d'ouvrages en bijouterie, joaillerie et orf\xe8vrerie",
 'B1604': u'R\xe9paration - montage en syst\xe8mes horlogers',
 'B1701': u"Conservation et reconstitution d'esp\xe8ces animales",
 'B1801': u"R\xe9alisation d'articles de chapellerie",
 'B1802': u"R\xe9alisation d'articles en cuir et mat\xe9riaux souples (hors v\xeatement)",
 'B1803': u'R\xe9alisation de v\xeatements sur mesure ou en petite s\xe9rie',
 'B1804': u"R\xe9alisation d'ouvrages d'art en fils",
 'B1805': u'Stylisme',
 'B1806': u'Tapisserie - d\xe9coration en ameublement',
 'C1101': u"Conception - d\xe9veloppement produits d'assurances",
 'C1102': u'Conseil client\xe8le en assurances',
 'C1103': u'Courtage en assurances',
 'C1104': u"Direction d'exploitation en assurances",
 'C1105': u'\xc9tudes actuarielles en assurances',
 'C1106': u'Expertise risques en assurances',
 'C1107': u'Indemnisations en assurances',
 'C1108': u'Management de groupe et de service en assurances',
 'C1109': u'R\xe9daction et gestion en assurances',
 'C1110': u"Souscription d'assurances",
 'C1201': u'Accueil et services bancaires',
 'C1202': u'Analyse de cr\xe9dits et risques bancaires',
 'C1203': u'Relation clients banque/finance',
 'C1204': u'Conception et expertise produits bancaires et financiers',
 'C1205': u'Conseil en gestion de patrimoine financier',
 'C1206': u'Gestion de client\xe8le bancaire',
 'C1207': u'Management en exploitation bancaire',
 'C1301': u'Front office march\xe9s financiers',
 'C1302': u'Gestion back et middle-office march\xe9s financiers',
 'C1303': u'Gestion de portefeuilles sur les march\xe9s financiers',
 'C1401': u'Gestion en banque et assurance',
 'C1501': u'G\xe9rance immobili\xe8re',
 'C1502': u'Gestion locative immobili\xe8re',
 'C1503': u'Management de projet immobilier',
 'C1504': u'Transaction immobili\xe8re',
 'D1101': u'Boucherie',
 'D1102': u'Boulangerie - viennoiserie',
 'D1103': u'Charcuterie - traiteur',
 'D1104': u'P\xe2tisserie, confiserie, chocolaterie et glacerie',
 'D1105': u'Poissonnerie',
 'D1106': u'Vente en alimentation',
 'D1107': u'Vente en gros de produits frais',
 'D1201': u"Achat vente d'objets d'art, anciens ou d'occasion",
 'D1202': u'Coiffure',
 'D1203': u'Hydroth\xe9rapie',
 'D1204': u'Location de v\xe9hicules ou de mat\xe9riel de loisirs',
 'D1205': u"Nettoyage d'articles textiles ou cuirs",
 'D1206': u"R\xe9paration d'articles en cuir et mat\xe9riaux souples",
 'D1207': u'Retouches en habillement',
 'D1208': u'Soins esth\xe9tiques et corporels',
 'D1209': u'Vente de v\xe9g\xe9taux',
 'D1210': u'Vente en animalerie',
 'D1211': u'Vente en articles de sport et loisirs',
 'D1212': u'Vente en d\xe9coration et \xe9quipement du foyer',
 'D1213': u'Vente en gros de mat\xe9riel et \xe9quipement',
 'D1214': u'Vente en habillement et accessoires de la personne',
 'D1301': u'Management de magasin de d\xe9tail',
 'D1401': u'Assistanat commercial',
 'D1404': u'Relation commerciale en vente de v\xe9hicules',
 'D1405': u'Conseil en information m\xe9dicale',
 'D1408': u'T\xe9l\xe9conseil et t\xe9l\xe9vente',
 'D1501': u'Animation de vente',
 'D1502': u'Management/gestion de rayon produits alimentaires',
 'D1503': u'Management/gestion de rayon produits non alimentaires',
 'D1504': u'Direction de magasin de grande distribution',
 'D1505': u'Personnel de caisse',
 'D1506': u'Marchandisage',
 'D1507': u'Mise en rayon libre-service',
 'D1508': u'Encadrement du personnel de caisses',
 'D1509': u'Management de d\xe9partement en grande distribution',
 'E1101': u'Animation de site multim\xe9dia',
 'E1102': u"Ecriture d'ouvrages, de livres",
 'E1103': u'Communication',
 'E1104': u'Conception de contenus multim\xe9dias',
 'E1105': u"Coordination d'\xe9dition",
 'E1106': u'Journalisme et information m\xe9dia',
 'E1107': u"Organisation d'\xe9v\xe9nementiel",
 'E1108': u'Traduction, interpr\xe9tariat',
 'E1201': u'Photographie',
 'E1202': u'Production en laboratoire cin\xe9matographique',
 'E1203': u'Production en laboratoire photographique',
 'E1204': u'Projection cin\xe9ma',
 'E1205': u'R\xe9alisation de contenus multim\xe9dias',
 'E1301': u"Conduite de machines d'impression",
 'E1302': u'Conduite de machines de fa\xe7onnage routage',
 'E1303': u'Encadrement des industries graphiques',
 'E1304': u'Fa\xe7onnage et routage',
 'E1305': u'Pr\xe9paration et correction en \xe9dition et presse',
 'E1306': u'Pr\xe9presse',
 'E1307': u'Reprographie',
 'E1308': u'Intervention technique en industrie graphique',
 'E1401': u'D\xe9veloppement et promotion publicitaire',
 'E1402': u'\xc9laboration de plan m\xe9dia',
 'F1101': u'Architecture du BTP',
 'F1102': u"Conception - am\xe9nagement d'espaces int\xe9rieurs",
 'F1103': u'Contr\xf4le et diagnostic technique du b\xe2timent',
 'F1104': u'Dessin BTP',
 'F1105': u'\xc9tudes g\xe9ologiques',
 'F1106': u'Ing\xe9nierie et \xe9tudes du BTP',
 'F1107': u'Mesures topographiques',
 'F1108': u'M\xe9tr\xe9 de la construction',
 'F1201': u'Conduite de travaux du BTP',
 'F1202': u'Direction de chantier du BTP',
 'F1203': u"Direction et ing\xe9nierie d'exploitation de gisements et de carri\xe8res",
 'F1204': u'S\xe9curit\xe9 et protection sant\xe9 du BTP',
 'F1301': u'Conduite de grue',
 'F1302': u"Conduite d'engins de terrassement et de carri\xe8re",
 'F1401': u'Extraction liquide et gazeuse',
 'F1402': u'Extraction solide',
 'F1501': u'Montage de structures et de charpentes bois',
 'F1502': u'Montage de structures m\xe9talliques',
 'F1503': u"R\xe9alisation - installation d'ossatures bois",
 'F1601': u'Application et d\xe9coration en pl\xe2tre, stuc et staff',
 'F1602': u'\xc9lectricit\xe9 b\xe2timent',
 'F1603': u"Installation d'\xe9quipements sanitaires et thermiques",
 'F1604': u"Montage d'agencements",
 'F1605': u'Montage de r\xe9seaux \xe9lectriques et t\xe9l\xe9coms',
 'F1606': u'Peinture en b\xe2timent',
 'F1607': u'Pose de fermetures menuis\xe9es',
 'F1608': u'Pose de rev\xeatements rigides',
 'F1609': u'Pose de rev\xeatements souples',
 'F1610': u'Pose et restauration de couvertures',
 'F1611': u'R\xe9alisation et restauration de fa\xe7ades',
 'F1612': u'Taille et d\xe9coration de pierres',
 'F1613': u"Travaux d'\xe9tanch\xe9it\xe9 et d'isolation",
 'F1701': u'Construction en b\xe9ton',
 'F1702': u'Construction de routes et voies',
 'F1703': u'Ma\xe7onnerie',
 'F1704': u'Pr\xe9paration du gros oeuvre et des travaux publics',
 'F1705': u'Pose de canalisations',
 'F1706': u'Pr\xe9fabrication en b\xe9ton industriel',
 'G1101': u'Accueil touristique',
 'G1102': u'Promotion du tourisme local',
 'G1201': u"Accompagnement de voyages, d'activit\xe9s culturelles ou sportives",
 'G1202': u"Animation d'activit\xe9s culturelles ou ludiques",
 'G1203': u"Animation de loisirs aupr\xe8s d'enfants ou d'adolescents",
 'G1204': u'\xc9ducation en activit\xe9s sportives',
 'G1205': u"Personnel d'attractions ou de structures de loisirs",
 'G1206': u'Personnel technique des jeux',
 'G1301': u'Conception de produits touristiques',
 'G1302': u'Optimisation de produits touristiques',
 'G1303': u'Vente de voyages',
 'G1401': u"Assistance de direction d'h\xf4tel-restaurant",
 'G1402': u"Management d'h\xf4tel-restaurant",
 'G1403': u"Gestion de structure de loisirs ou d'h\xe9bergement touristique",
 'G1404': u"Management d'\xe9tablissement de restauration collective",
 'G1501': u"Personnel d'\xe9tage",
 'G1502': u"Personnel polyvalent d'h\xf4tellerie",
 'G1503': u"Management du personnel d'\xe9tage",
 'G1601': u'Management du personnel de cuisine',
 'G1602': u'Personnel de cuisine',
 'G1603': u'Personnel polyvalent en restauration',
 'G1604': u'Fabrication de cr\xeapes ou pizzas',
 'G1605': u'Plonge en restauration',
 'G1701': u'Conciergerie en h\xf4tellerie',
 'G1702': u'Personnel du hall',
 'G1703': u'R\xe9ception en h\xf4tellerie',
 'G1801': u'Caf\xe9, bar brasserie',
 'G1802': u'Management du service en restauration',
 'G1803': u'Service en restauration',
 'G1804': u'Sommellerie',
 'H1102': u"Management et ing\xe9nierie d'affaires",
 'H1201': u'Expertise technique couleur en industrie',
 'H1202': u'Conception et dessin de produits \xe9lectriques et \xe9lectroniques',
 'H1204': u'Design industriel',
 'H1205': u'\xc9tudes - mod\xe8les en industrie des mat\xe9riaux souples',
 'H1206': u'Management et ing\xe9nierie \xe9tudes, recherche et d\xe9veloppement industriel',
 'H1209': u'Intervention technique en \xe9tudes et d\xe9veloppement \xe9lectronique',
 'H1301': u'Inspection de conformit\xe9',
 'H1302': u'Management et ing\xe9nierie Hygi\xe8ne S\xe9curit\xe9 Environnement -HSE- industriels',
 'H1303': u'Intervention technique en Hygi\xe8ne S\xe9curit\xe9 Environnement  -HSE- industriel',
 'H1401': u'Management et ing\xe9nierie gestion industrielle et logistique',
 'H1402': u'Management et ing\xe9nierie m\xe9thodes et industrialisation',
 'H1501': u"Direction de laboratoire d'analyse industrielle",
 'H1502': u'Management et ing\xe9nierie qualit\xe9 industrielle',
 'H1503': u"Intervention technique en laboratoire d'analyse industrielle",
 'H1504': u'Intervention technique en contr\xf4le essai qualit\xe9 en \xe9lectricit\xe9 et \xe9lectronique',
 'H1505': u'Intervention technique en formulation et analyse sensorielle',
 'H1506': u'Intervention technique qualit\xe9 en m\xe9canique et travail des m\xe9taux',
 'H2101': u'Abattage et d\xe9coupe des viandes',
 'H2102': u"Conduite d'\xe9quipement de production alimentaire",
 'H2201': u"Assemblage d'ouvrages en bois",
 'H2202': u"Conduite d'\xe9quipement de fabrication de l'ameublement et du bois",
 'H2203': u"Conduite d'installation de production de panneaux bois",
 'H2204': u"Encadrement des industries de l'ameublement et du bois",
 'H2205': u"Premi\xe8re transformation de bois d'oeuvre",
 'H2206': u'R\xe9alisation de menuiserie bois et tonnellerie',
 'H2207': u'R\xe9alisation de meubles en bois',
 'H2208': u"R\xe9alisation d'ouvrages d\xe9coratifs en bois",
 'H2209': u'Intervention technique en ameublement et bois',
 'H2301': u"Conduite d'\xe9quipement de production chimique ou pharmaceutique",
 'H2401': u"Assemblage - montage d'articles en cuirs, peaux",
 'H2402': u'Assemblage - montage de v\xeatements et produits textiles',
 'H2403': u'Conduite de machine de fabrication de produits textiles',
 'H2404': u'Conduite de machine de production et transformation des fils',
 'H2405': u'Conduite de machine de textiles nontiss\xe9s',
 'H2406': u'Conduite de machine de traitement textile',
 'H2407': u'Conduite de machine de transformation et de finition des cuirs et peaux',
 'H2408': u"Conduite de machine d'impression textile",
 'H2409': u'Coupe cuir, textile et mat\xe9riaux souples',
 'H2410': u'Mise en forme, repassage et finitions en industrie textile',
 'H2411': u'Montage de prototype cuir et mat\xe9riaux souples',
 'H2412': u'Patronnage - gradation',
 'H2413': u'Pr\xe9paration de fils, montage de m\xe9tiers textiles',
 'H2414': u"Pr\xe9paration et finition d'articles en cuir et mat\xe9riaux souples",
 'H2415': u'Contr\xf4le en industrie du cuir et du textile',
 'H2501': u'Encadrement de production de mat\xe9riel \xe9lectrique et \xe9lectronique',
 'H2503': u"Pilotage d'unit\xe9 \xe9l\xe9mentaire de production m\xe9canique",
 'H2504': u"Encadrement d'\xe9quipe en industrie de transformation",
 'H2505': u"Encadrement d'\xe9quipe ou d'atelier en mat\xe9riaux souples",
 'H2601': u'Bobinage \xe9lectrique',
 'H2602': u'C\xe2blage \xe9lectrique et \xe9lectrom\xe9canique',
 'H2603': u"Conduite d'installation automatis\xe9e de production \xe9lectrique, \xe9lectronique et micro\xe9lectronique",
 'H2604': u'Montage de produits \xe9lectriques et \xe9lectroniques',
 'H2605': u'Montage et c\xe2blage \xe9lectronique',
 'H2701': u"Pilotage d'installation \xe9nerg\xe9tique et p\xe9trochimique",
 'H2801': u"Conduite d'\xe9quipement de transformation du verre",
 'H2802': u"Conduite d'installation de production de mat\xe9riaux de construction",
 'H2803': u'Fa\xe7onnage et \xe9maillage en industrie c\xe9ramique',
 'H2804': u"Pilotage de centrale \xe0 b\xe9ton pr\xeat \xe0 l'emploi, ciment, enrob\xe9s et granulats",
 'H2805': u"Pilotage d'installation de production verri\xe8re",
 'H2901': u'Ajustement et montage de fabrication',
 'H2902': u'Chaudronnerie - t\xf4lerie',
 'H2903': u"Conduite d'\xe9quipement d'usinage",
 'H2904': u"Conduite d'\xe9quipement de d\xe9formation des m\xe9taux",
 'H2905': u"Conduite d'\xe9quipement de formage et d\xe9coupage des mat\xe9riaux",
 'H2906': u"Conduite d'installation automatis\xe9e ou robotis\xe9e de fabrication m\xe9canique",
 'H2907': u"Conduite d'installation de production des m\xe9taux",
 'H2908': u'Modelage de mat\xe9riaux non m\xe9talliques',
 'H2909': u'Montage-assemblage m\xe9canique',
 'H2910': u'Moulage sable',
 'H2911': u'R\xe9alisation de structures m\xe9talliques',
 'H2914': u'R\xe9alisation et montage en tuyauterie',
 'H3101': u"Conduite d'\xe9quipement de fabrication de papier ou de carton",
 'H3102': u"Conduite d'installation de p\xe2te \xe0 papier",
 'H3201': u"Conduite d'\xe9quipement de formage des plastiques et caoutchoucs",
 'H3202': u"R\xe9glage d'\xe9quipement de formage des plastiques et caoutchoucs",
 'H3203': u'Fabrication de pi\xe8ces en mat\xe9riaux composites',
 'H3301': u"Conduite d'\xe9quipement de conditionnement",
 'H3302': u"Op\xe9rations manuelles d'assemblage, tri ou emballage",
 'H3303': u'Pr\xe9paration de mati\xe8res et produits industriels (broyage, m\xe9lange, \u2026)',
 'H3401': u"Conduite de traitement d'abrasion de surface",
 'H3402': u'Conduite de traitement par d\xe9p\xf4t de surface',
 'H3403': u'Conduite de traitement thermique',
 'H3404': u'Peinture industrielle',
 'I1201': u"Entretien d'affichage et mobilier urbain",
 'I1202': u'Entretien et surveillance du trac\xe9 routier',
 'I1203': u'Maintenance des b\xe2timents et des locaux',
 'I1301': u"Installation et maintenance d'ascenseurs",
 'I1302': u"Installation et maintenance d'automatismes",
 'I1303': u'Installation et maintenance de distributeurs automatiques',
 'I1304': u"Installation et maintenance d'\xe9quipements industriels et d'exploitation",
 'I1305': u'Installation et maintenance \xe9lectronique',
 'I1306': u"Installation et maintenance en froid, conditionnement d'air",
 'I1307': u'Installation et maintenance t\xe9l\xe9coms et courants faibles',
 'I1308': u"Maintenance d'installation de chauffage",
 'I1309': u'Maintenance \xe9lectrique',
 'I1310': u'Maintenance m\xe9canique industrielle',
 'I1401': u'Maintenance informatique et bureautique',
 'I1402': u'R\xe9paration de biens \xe9lectrodomestiques',
 'I1501': u'Intervention en grande hauteur',
 'I1502': u'Intervention en milieu subaquatique',
 'I1503': u'Intervention en milieux et produits nocifs',
 'I1601': u'Installation et maintenance en nautisme',
 'I1602': u"Maintenance d'a\xe9ronefs",
 'I1603': u"Maintenance d'engins de chantier, levage, manutention et de machines agricoles",
 'I1604': u'M\xe9canique automobile',
 'I1605': u'M\xe9canique de marine',
 'I1606': u'R\xe9paration de carrosserie',
 'I1607': u'R\xe9paration de cycles, motocycles et motoculteurs de loisirs',
 'J1101': u'M\xe9decine de pr\xe9vention',
 'J1102': u'M\xe9decine g\xe9n\xe9raliste et sp\xe9cialis\xe9e',
 'J1103': u'M\xe9decine dentaire',
 'J1104': u"Suivi de la grossesse et de l'accouchement",
 'J1201': u'Biologie m\xe9dicale',
 'J1202': u'Pharmacie',
 'J1301': u'Personnel polyvalent des services hospitaliers',
 'J1302': u'Analyses m\xe9dicales',
 'J1303': u'Assistance m\xe9dico-technique',
 'J1304': u'Aide en pu\xe9riculture',
 'J1305': u'Conduite de v\xe9hicules sanitaires',
 'J1306': u'Imagerie m\xe9dicale',
 'J1307': u'Pr\xe9paration en pharmacie',
 'J1401': u'Audioproth\xe8ses',
 'J1402': u'Di\xe9t\xe9tique',
 'J1403': u'Ergoth\xe9rapie',
 'J1404': u'Kin\xe9sith\xe9rapie',
 'J1405': u'Optique - lunetterie',
 'J1406': u'Orthophonie',
 'J1407': u'Orthoptique',
 'J1408': u'Ost\xe9opathie et chiropraxie',
 'J1409': u'P\xe9dicurie et podologie',
 'J1410': u'Proth\xe8ses dentaires',
 'J1411': u'Proth\xe8ses et orth\xe8ses',
 'J1412': u'R\xe9\xe9ducation en psychomotricit\xe9',
 'J1501': u"Soins d'hygi\xe8ne, de confort du patient",
 'J1502': u'Coordination de services m\xe9dicaux ou param\xe9dicaux',
 'J1503': u'Soins infirmiers sp\xe9cialis\xe9s en anesth\xe9sie',
 'J1504': u'Soins infirmiers sp\xe9cialis\xe9s en bloc op\xe9ratoire',
 'J1505': u'Soins infirmiers sp\xe9cialis\xe9s en pr\xe9vention',
 'J1506': u'Soins infirmiers g\xe9n\xe9ralistes',
 'J1507': u'Soins infirmiers sp\xe9cialis\xe9s en pu\xe9riculture',
 'K1101': u'Accompagnement et m\xe9diation familiale',
 'K1102': u"Aide aux b\xe9n\xe9ficiaires d'une mesure de protection juridique",
 'K1103': u'D\xe9veloppement personnel et bien-\xeatre de la personne',
 'K1104': u'Psychologie',
 'K1201': u'Action sociale',
 'K1202': u'\xc9ducation de jeunes enfants',
 'K1203': u'Encadrement technique en insertion professionnelle',
 'K1204': u'Facilitation de la vie sociale',
 'K1205': u'Information et m\xe9diation sociale',
 'K1206': u'Intervention socioculturelle',
 'K1207': u'Intervention socio\xe9ducative',
 'K1301': u'Accompagnement m\xe9dicosocial',
 'K1302': u"Assistance aupr\xe8s d'adultes",
 'K1303': u"Assistance aupr\xe8s d'enfants",
 'K1304': u'Services domestiques',
 'K1305': u'Intervention sociale et familiale',
 'K1401': u'Conception et pilotage de la politique des pouvoirs publics',
 'K1402': u'Conseil en Sant\xe9 Publique',
 'K1403': u'Management de structure de sant\xe9, sociale ou p\xe9nitentiaire',
 'K1404': u'Mise en oeuvre et pilotage de la politique des pouvoirs publics',
 'K1405': u"Repr\xe9sentation de l'Etat sur le territoire national ou international",
 'K1501': u'Application des r\xe8gles financi\xe8res publiques',
 'K1502': u'Contr\xf4le et inspection des Affaires Sociales',
 'K1503': u'Contr\xf4le et inspection des imp\xf4ts',
 'K1504': u'Contr\xf4le et inspection du Tr\xe9sor Public',
 'K1505': u'Protection des consommateurs et contr\xf4le des \xe9changes commerciaux',
 'K1601': u"Gestion de l'information et de la documentation",
 'K1602': u'Gestion de patrimoine culturel',
 'K1701': u'Personnel de la D\xe9fense',
 'K1702': u'Direction de la s\xe9curit\xe9 civile et des secours',
 'K1703': u'Direction op\xe9rationnelle de la d\xe9fense',
 'K1704': u'Management de la s\xe9curit\xe9 publique',
 'K1705': u'S\xe9curit\xe9 civile et secours',
 'K1706': u'S\xe9curit\xe9 publique',
 'K1707': u'Surveillance municipale',
 'K1801': u'Conseil en emploi et insertion socioprofessionnelle',
 'K1802': u'D\xe9veloppement local',
 'K1901': u'Aide et m\xe9diation judiciaire',
 'K1902': u'Collaboration juridique',
 'K1903': u'D\xe9fense et conseil juridique',
 'K1904': u'Magistrature',
 'K2101': u'Conseil en formation',
 'K2102': u'Coordination p\xe9dagogique',
 'K2103': u"Direction d'\xe9tablissement et d'enseignement",
 'K2104': u"\xc9ducation et surveillance au sein d'\xe9tablissements d'enseignement",
 'K2105': u'Enseignement artistique',
 'K2106': u'Enseignement des \xe9coles',
 'K2107': u'Enseignement g\xe9n\xe9ral du second degr\xe9',
 'K2108': u'Enseignement sup\xe9rieur',
 'K2109': u'Enseignement technique et professionnel',
 'K2110': u'Formation en conduite de v\xe9hicules',
 'K2111': u'Formation professionnelle',
 'K2112': u'Orientation scolaire et professionnelle',
 'K2201': u'Blanchisserie industrielle',
 'K2202': u'Lavage de vitres',
 'K2203': u'Management et inspection en propret\xe9 de locaux',
 'K2204': u'Nettoyage de locaux',
 'K2301': u"Distribution et assainissement d'eau",
 'K2302': u'Management et inspection en environnement urbain',
 'K2303': u'Nettoyage des espaces urbains',
 'K2304': u'Revalorisation de produits industriels',
 'K2305': u'Salubrit\xe9 et traitement de nuisibles',
 'K2306': u"Supervision d'exploitation \xe9co-industrielle",
 'K2401': u"Recherche en sciences de l'homme et de la soci\xe9t\xe9",
 'K2402': u"Recherche en sciences de l'univers, de la mati\xe8re et du vivant",
 'K2501': u'Gardiennage de locaux',
 'K2502': u'Management de s\xe9curit\xe9 priv\xe9e',
 'K2503': u'S\xe9curit\xe9 et surveillance priv\xe9es',
 'K2601': u"Conduite d'op\xe9rations fun\xe9raires",
 'K2602': u'Conseil en services fun\xe9raires',
 'K2603': u'Thanatopraxie',
 'L1101': u'Animation musicale et sc\xe9nique',
 'L1102': u'Mannequinat et pose artistique',
 'L1103': u"Pr\xe9sentation de spectacles ou d'\xe9missions",
 'L1201': u'Danse',
 'L1202': u'Musique et chant',
 'L1203': u'Art dramatique',
 'L1204': u'Arts du cirque et arts visuels',
 'L1301': u'Mise en sc\xe8ne de spectacles vivants',
 'L1302': u'Production et administration spectacle, cin\xe9ma et audiovisuel',
 'L1303': u"Promotion d'artistes et de spectacles",
 'L1304': u'R\xe9alisation cin\xe9matographique et audiovisuelle',
 'L1401': u'Sportif professionnel',
 'L1501': u'Coiffure et maquillage spectacle',
 'L1502': u'Costume et habillage spectacle',
 'L1503': u'D\xe9cor et accessoires spectacle',
 'L1504': u'\xc9clairage spectacle',
 'L1505': u'Image cin\xe9matographique et t\xe9l\xe9visuelle',
 'L1506': u'Machinerie spectacle',
 'L1507': u'Montage et post-production',
 'L1508': u'Prise de son et sonorisation',
 'L1509': u'R\xe9gie g\xe9n\xe9rale',
 'M1101': u'Achats',
 'M1102': u'Direction des achats',
 'M1201': u'Analyse et ing\xe9nierie financi\xe8re',
 'M1202': u'Audit et contr\xf4le comptables et financiers',
 'M1203': u'Comptabilit\xe9',
 'M1204': u'Contr\xf4le de gestion',
 'M1205': u'Direction administrative et financi\xe8re',
 'M1206': u'Management de groupe ou de service comptable',
 'M1207': u'Tr\xe9sorerie et financement',
 'M1401': u"Conduite d'enqu\xeates",
 'M1402': u"Conseil en organisation et management d'entreprise",
 'M1403': u'\xc9tudes et prospectives socio-\xe9conomiques',
 'M1404': u"Management et gestion d'enqu\xeates",
 'M1501': u'Assistanat en ressources humaines',
 'M1502': u'D\xe9veloppement des ressources humaines',
 'M1503': u'Management des ressources humaines',
 'M1601': u'Accueil et renseignements',
 'M1602': u'Op\xe9rations administratives',
 'M1603': u'Distribution de documents',
 'M1604': u'Assistanat de direction',
 'M1605': u'Assistanat technique et administratif',
 'M1606': u'Saisie de donn\xe9es',
 'M1607': u'Secr\xe9tariat',
 'M1608': u'Secr\xe9tariat comptable',
 'M1609': u'Secr\xe9tariat et assistanat m\xe9dical ou m\xe9dico-social',
 'M1701': u'Administration des ventes',
 'M1702': u'Analyse de tendance',
 'M1703': u'Management et gestion de produit',
 'M1704': u'Management relation client\xe8le',
 'M1705': u'Marketing',
 'M1706': u'Promotion des ventes',
 'M1707': u'Strat\xe9gie commerciale',
 'M1801': u"Administration de syst\xe8mes d'information",
 'M1802': u"Conseil et ma\xeetrise d'ouvrage en syst\xe8mes d'information",
 'M1803': u"Direction des syst\xe8mes d'information",
 'M1804': u'\xc9tudes et d\xe9veloppement de r\xe9seaux de t\xe9l\xe9coms',
 'M1805': u'\xc9tudes et d\xe9veloppement informatique',
 'M1806': u"Expertise et support technique en syst\xe8mes d'information",
 'M1807': u'Exploitation de syst\xe8mes de communication et de commandement',
 'M1808': u'Information g\xe9ographique',
 'M1809': u'Information m\xe9t\xe9orologique',
 'M1810': u"Production et exploitation de syst\xe8mes d'information",
 'N1101': u"Conduite d'engins de d\xe9placement des charges",
 'N1102': u'D\xe9m\xe9nagement',
 'N1103': u'Magasinage et pr\xe9paration de commandes',
 'N1104': u"Manoeuvre et conduite d'engins lourds de manutention",
 'N1105': u'Manutention manuelle de charges',
 'N1201': u'Affr\xe8tement transport',
 'N1202': u'Gestion des op\xe9rations de circulation internationale des marchandises',
 'N1301': u'Conception et organisation de la cha\xeene logistique',
 'N1302': u'Direction de site logistique',
 'N1303': u"Intervention technique d'exploitation logistique",
 'N2101': u'Navigation commerciale a\xe9rienne',
 'N2102': u'Pilotage et navigation technique a\xe9rienne',
 'N2201': u"Personnel d'escale a\xe9roportuaire",
 'N2202': u'Contr\xf4le de la navigation a\xe9rienne',
 'N2203': u'Exploitation des pistes a\xe9roportuaires',
 'N2204': u'Pr\xe9paration des vols',
 'N2205': u"Direction d'escale et exploitation a\xe9roportuaire",
 'N3101': u'Encadrement de la navigation maritime',
 'N3102': u'Equipage de la navigation maritime',
 'N3103': u'Navigation fluviale',
 'N3201': u'Exploitation des op\xe9rations portuaires et du transport maritime',
 'N3202': u'Exploitation du transport fluvial',
 'N3203': u'Manutention portuaire',
 'N4101': u'Conduite de transport de marchandises sur longue distance',
 'N4102': u'Conduite de transport de particuliers',
 'N4103': u'Conduite de transport en commun sur route',
 'N4104': u'Courses et livraisons express',
 'N4105': u'Conduite et livraison par tourn\xe9es sur courte distance',
 'N4201': u"Direction d'exploitation des transports routiers de marchandises",
 'N4202': u"Direction d'exploitation des transports routiers de personnes",
 'N4203': u"Intervention technique d'exploitation des transports routiers de marchandises",
 'N4204': u"Intervention technique d'exploitation des transports routiers de personnes",
 'N4301': u'Conduite sur rails',
 'N4302': u'Contr\xf4le des transports en commun',
 'N4401': u'Circulation du r\xe9seau ferr\xe9',
 'N4402': u'Exploitation et manoeuvre des remont\xe9es m\xe9caniques',
 'N4403': u'Manoeuvre du r\xe9seau ferr\xe9',
 # missing rome code (2016-03-17)
 'D1402': u'Relation commerciale grands comptes et entreprises',
 'D1403': u'Relation commerciale auprès de particuliers',
 'D1406': u'Management en force de vente',
 'D1407': u'Relation technico-commerciale',
 'H1101': u'Assistance et support technique client',
 'H1207': u'Rédaction technique',
 'H1208': u'Intervention technique en études et conception en automatisme',
 'H1210': u'Intervention technique en études, recherche et développement',
 'H1403': u'Intervention technique en gestion industrielle et logistique',
 'H1404': u'Intervention technique en méthodes et industrialisation',
 'H2502': u'Management et ingénierie de production',
 'H2912': u'Réglage d\'équipement de production industrielle',
 'H2913': u'Soudage manuel',
 'I1101': u'Direction et ingénierie en entretien infrastructure et bâti',
 'I1102': u'Management et ingénierie de maintenance industrielle',
 'I1103': u'Supervision d\'entretien et gestion de véhicules',
 'M1301': u'Direction de grande entreprise ou d\'établissement public',
 'M1302': u'Direction de petite ou moyenne entreprise',
 'H1203': u'Conception et dessin produits mécaniques'
 }
