ENABLE_CAR_MODE = True
ENABLE_PUBLIC_MODE = True

ISOCHRONE_DURATIONS_MINUTES = (15, 30, 45)

CAR_MODE = 'car'
PUBLIC_MODE = 'public'

TRAVEL_MODES = ()
if ENABLE_PUBLIC_MODE:
    TRAVEL_MODES += (PUBLIC_MODE,)
if ENABLE_CAR_MODE:
    TRAVEL_MODES += (CAR_MODE,)

if ENABLE_CAR_MODE:
    DEFAULT_TRAVEL_MODE = CAR_MODE
else:
    DEFAULT_TRAVEL_MODE = PUBLIC_MODE

TRAVEL_MODES_FRENCH = {
    CAR_MODE: 'Voiture',
    PUBLIC_MODE: 'Transports en commun',
}
