ISOCHRONE_DURATIONS_MINUTES = (15, 30, 45)

CAR_MODE = 'car'
PUBLIC_MODE = 'public'

DEFAULT_TRAVEL_MODE = CAR_MODE

TRAVEL_MODES = (
    PUBLIC_MODE,
    CAR_MODE,
)

TRAVEL_MODES_FRENCH = {
    CAR_MODE: 'Voiture',
    PUBLIC_MODE: 'Transports en commun',
}
